-- MySQL Script generated by MySQL Workbench
-- Fri Oct 23 11:55:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GiftService
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GiftService` ;

-- -----------------------------------------------------
-- Schema GiftService
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GiftService` DEFAULT CHARACTER SET utf8 ;
USE `GiftService` ;

-- -----------------------------------------------------
-- Table `GiftService`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GiftService`.`Tag` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GiftService`.`GiftCertificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GiftService`.`GiftCertificate` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NOT NULL,
  `Price` DECIMAL(7,2) NOT NULL,
  `CreateDate` TIMESTAMP NOT NULL,
  `LastUpdateDate` TIMESTAMP NULL,
  `Duration` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GiftService`.`Tag-Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GiftService`.`Tag-Certificate` (
  `IdTag` BIGINT NOT NULL,
  `IdCertificate` BIGINT NOT NULL,
  INDEX `GiftSertificateTag_SertificateFK_idx` (`IdCertificate` ASC) VISIBLE,
  INDEX `TagTag_SertificateFK_idx` (`IdTag` ASC) VISIBLE,
  CONSTRAINT `GiftCertificateTag_CertificateFK`
    FOREIGN KEY (`IdCertificate`)
    REFERENCES `GiftService`.`GiftCertificate` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TagTag_CertificateFK`
    FOREIGN KEY (`IdTag`)
    REFERENCES `GiftService`.`Tag` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `GiftService`.`Tag`
-- -----------------------------------------------------
START TRANSACTION;
USE `GiftService`;
INSERT INTO `GiftService`.`Tag` (`Id`, `Name`) VALUES (1, '#Sport');
INSERT INTO `GiftService`.`Tag` (`Id`, `Name`) VALUES (2, '#Romance');

COMMIT;


-- -----------------------------------------------------
-- Data for table `GiftService`.`GiftCertificate`
-- -----------------------------------------------------
START TRANSACTION;
USE `GiftService`;
INSERT INTO `GiftService`.`GiftCertificate` (`Id`, `Name`, `Description`, `Price`, `CreateDate`, `LastUpdateDate`, `Duration`) VALUES (1, 'Skydiving', 'For 1 person', 50.0, '20201019124030', NULL, 90);
INSERT INTO `GiftService`.`GiftCertificate` (`Id`, `Name`, `Description`, `Price`, `CreateDate`, `LastUpdateDate`, `Duration`) VALUES (2, 'Skydiving', 'For 2 persons', 90.0, '20201019124030', NULL, 90);
INSERT INTO `GiftService`.`GiftCertificate` (`Id`, `Name`, `Description`, `Price`, `CreateDate`, `LastUpdateDate`, `Duration`) VALUES (3, 'Dinner by candlelight ', 'For couple in the restorant \"Troffea\"', 10.50, '20201019124030', NULL, 90);

COMMIT;


-- -----------------------------------------------------
-- Data for table `GiftService`.`Tag-Certificate`
-- -----------------------------------------------------
START TRANSACTION;
USE `GiftService`;
INSERT INTO `GiftService`.`Tag-Certificate` (`IdTag`, `IdCertificate`) VALUES (1, 1);
INSERT INTO `GiftService`.`Tag-Certificate` (`IdTag`, `IdCertificate`) VALUES (1, 2);
INSERT INTO `GiftService`.`Tag-Certificate` (`IdTag`, `IdCertificate`) VALUES (2, 3);

COMMIT;

